project:
  type: website
  output-dir: docs

website:
  title: "Homer White's Website Warmup"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 

  sidebar:
    - id: articles
      title: "Articles"
      style: "docked"
      background: light
      collapse-level: 2
      contents: 
        - text: "Advent of Code 2022"
          href:  articles/article_01.qmd
        - text: "Browser Implementation"
          href:  articles/article_02.qmd
        - text: "Canvas Battleship"
          href:  articles/battleship/index.qmd

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



