project:
  type: website
  output-dir: docs

website:
  title: "Homer White's Website"
  site-path: "/personal-homer-white/"
  reader-mode: true
  repo-url: https://github.com/homerhanumat/personal-homer-white
  repo-actions: issue
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: articles/index.qmd
        text: Articles 
      - href: posts/index.qmd
        text: Blog

  sidebar:

    - id: none
      style: "docked"
      background: light
      collapse-level: 2
      contents:
        - section: "Articles"
          href: articles/index.qmd
          contents: 
            - text: "Advent of Code 2022"
              href:  articles/advent/index.qmd
            - text: "Browser Implementation"
              href:  articles/browser/index.qmd
            - text: "Canvas Battleship"
              href:  articles/battleship/index.qmd
            - text: "Observables Scatterplot"
              href: articles/scatterplot/index.qmd
            - text: "Stock Prices"
              href: articles/stocks/index.qmd
            - text: "Arquero Wrangling"
              href: articles/homerunleaders/index.qmd
        - section: "Posts"
          href: posts/index.qmd
          contents: "posts/*/*.qmd"


format:
  html:
    theme: flatly
    css: styles.css
    toc: true

# execute:
#   freeze: true



